run_name: demo_local_transformers_qwen3_squad
output_dir: outputs
batch_size: 1


dataset:
  dataset_id: AIME25
  source: local
  name: AIME25
  path: /home/yann.meng/workspaces/datasets/TIGER-Lab/AIME25
  split: validation
  input_column: question
  answer_column: answers
  limit: 50

model:
  backend: transformers
  task_type: llm
  model_source: local
  model_name_or_path: /home/yann.meng/workspaces/modelscope/Qwen/Qwen3-4B-Instruct
  torch_dtype: bfloat16
  device_map: auto
  max_new_tokens: 128
  temperature: 0.0

metrics:
  names: [exact_match, token_f1, rouge_l, char_f1]
